FROM node:20-alpine AS builder

WORKDIR /app

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

COPY package*.json ./
RUN npm install --production=false

COPY . .
RUN npm run build

# ---- Runtime ----
FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app ./
ENV NODE_ENV=production

EXPOSE 3000
CMD ["npm", "start"]
